# set base image (host OS)
FROM pytorch/pytorch

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6 -y
RUN pip install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY src/ .
COPY models/ .

# testing
RUN python -m unittest tests.TestUtils